all:
	pdflatex SolutionDiscussion.tex
	pdflatex SolutionDiscussion.tex

test:
	pdflatex SingleProblem.tex
	pdflatex SingleProblem.tex

clean:
	rm -f *.aux *.dvi *.log *.out *.toc

sources:
	cd Solutions && javac *.java
